# Generated by Django 5.2.11 on 2026-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('followers', models.BigIntegerField(default=0)),
                ('post_date', models.DateTimeField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('raw_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_loto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ScrapeResult',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ig', 'Instagram'), ('tk', 'TikTok'), ('x', 'X/Twitter'), ('yt', 'YouTube'), ('fb', 'Facebook')], max_length=2)),
                ('key_value', models.TextField()),
                ('purpose', models.CharField(default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ScraperKey',
            },
        ),
    ]
