# Generated by Django 5.2.11 on 2026-03-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperesult',
            name='alegria',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='anticipacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='aversion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='confianza',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='ira',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='miedo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='sentimiento_global',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='sorpresa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='tristeza',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scraperkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
