# Generated by Django 4.2.30 on 2026-08-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_scraperesult_alegria_scraperesult_anticipacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperesult',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
