# Generated by Django 5.2.11 on 2026-03-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
    ]