# Generated by Django 4.2.30 on 2026-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_scraperesult_hashtags_alter_scraperesult_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperesult',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
