# Generated by Django 5.2.11 on 2026-03-26 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_backend', '0004_remove_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, default='', max_length=20)),
                ('targets', models.JSONField(default=list)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('DENIED', 'DENIED'), ('INVALID', 'INVALID'), ('ERROR', 'ERROR')], default='PENDING', max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ExtractionRequestLog',
                'ordering': ['-created_at'],
            },
        ),
    ]