# Generated by Django 5.2.11 on 2026-03-26 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('followers', models.BigIntegerField(default=0)),
                ('post_date', models.DateTimeField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('raw_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_loto', models.BooleanField(default=False)),
                ('sentimiento_global', models.CharField(default='N/A', max_length=50)),
                ('alegria', models.FloatField(default=0.0)),
                ('confianza', models.FloatField(default=0.0)),
                ('miedo', models.FloatField(default=0.0)),
                ('sorpresa', models.FloatField(default=0.0)),
                ('tristeza', models.FloatField(default=0.0)),
                ('aversion', models.FloatField(default=0.0)),
                ('ira', models.FloatField(default=0.0)),
                ('anticipacion', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'ScrapeResult',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ig', 'Instagram'), ('tk', 'TikTok'), ('x', 'X/Twitter'), ('yt', 'YouTube'), ('fb', 'Facebook')], max_length=2)),
                ('key_value', models.TextField()),
                ('purpose', models.CharField(default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ScraperKey',
            },
        ),
        migrations.CreateModel(
            name='ExtractionRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, default='', max_length=20)),
                ('targets', models.JSONField(default=list)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('DENIED', 'DENIED'), ('INVALID', 'INVALID'), ('ERROR', 'ERROR')], default='PENDING', max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ExtractionRequestLog',
                'ordering': ['-created_at'],
            },
        ),
    ]
